namespace MemoGenerator.Models
{
    public sealed class MemoDocument
    {
        public string? To { get; set; }
        public string? Through { get; set; }   // nullable by design
        public string? From { get; set; }
        public string? Subject { get; set; }
        public string? Body { get; set; }
        public string? Classification { get; set; }

        // Meta (auto-generated by controller if not provided)
        public string? MemoNumber { get; set; }
        public string? DateText { get; set; }

        // Styling options (service has fallbacks)
        public string? LabelColorHex { get; set; }
        public string? UnderlineColorHex { get; set; }
        public string? FontFamilyLatin { get; set; }
        public string? FontFamilyArabic { get; set; }

        // Layout
        public float PageMarginPt { get; set; } = 36f;

        // Images
        public byte[]? BannerImage { get; set; }
        public byte[]? FooterImage { get; set; }
    }
}
